version: "3.4"

x-app: &default-app
  depends_on:
    - "postgres"
  env_file:
    - ".env"
  restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
  stop_grace_period: "3s"
  tty: true

services:
  postgres:
    env_file:
      - ".env"
    image: "postgres:14.0"
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: "3s"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    container_name: "forecasts_db"

  web:
    <<: *default-app
    image: forecasts:latest
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    container_name: "forecasts_app"

volumes:
  postgres: {}